#pragma once

#include "Front/Module/Module.h"
#include <deque>
#include <utility>

namespace kelyra {
using ExpansionWorklist = std::deque<std::pair<lex::Node *, const Module *>>;
// Coordinate annotation expansion and generic materialization for declarations
// generated by either layer, before semantic analysis.
bool ExpandModules(const std::vector<const Module *> &Modules);
} // namespace kelyra
