//
// Created by zzm on 2026/9/18
// Part of RVision
//
#include "Lexer/Token.h"
#include <cassert>

std::string kelyra::lex::GetTokenName(TokenKind kind) {
  switch (kind) {
  case TokenKind::illegal:
    return "Illegal";
  case TokenKind::name:
    return "Name";
  case TokenKind::number:
    return "Number";
  case TokenKind::string:
    return "String";
  case TokenKind::asm_text:
    return "AsmText";
  case TokenKind::keyword_let:
    return "let";
  case TokenKind::keyword_var:
    return "var";
  case TokenKind::keyword_fn:
    return "fn";
  case TokenKind::keyword_struct:
    return "struct";
  case TokenKind::keyword_annotation:
    return "annotation";
  case TokenKind::keyword_if:
    return "if";
  case TokenKind::keyword_else:
    return "else";
  case TokenKind::keyword_while:
    return "while";
  case TokenKind::keyword_return:
    return "return";
  case TokenKind::keyword_break:
    return "break";
  case TokenKind::keyword_continue:
    return "continue";
  case TokenKind::keyword_true:
    return "true";
  case TokenKind::keyword_false:
    return "false";
  case TokenKind::keyword_meta:
    return "meta";
  case TokenKind::keyword_when:
    return "when";
  case TokenKind::keyword_parallel:
    return "parallel";
  case TokenKind::keyword_extern:
    return "extern";
  case TokenKind::keyword_defer:
    return "defer";
  case TokenKind::keyword_module:
    return "module";
  case TokenKind::keyword_import:
    return "import";
  case TokenKind::keyword_pub:
    return "pub";
  case TokenKind::keyword_asm:
    return "asm";
  case TokenKind::op_arrow:
    return "->";
  case TokenKind::op_assign:
    return "=";
  case TokenKind::op_add:
    return "+";
  case TokenKind::op_subtract:
    return "-";
  case TokenKind::op_multiply:
    return "*";
  case TokenKind::op_divide:
    return "/";
  case TokenKind::op_remainder:
    return "%";
  case TokenKind::op_equal:
    return "==";
  case TokenKind::op_not_equal:
    return "!=";
  case TokenKind::op_less:
    return "<";
  case TokenKind::op_less_equal:
    return "<=";
  case TokenKind::op_greater:
    return ">";
  case TokenKind::op_greater_equal:
    return ">=";
  case TokenKind::op_and:
    return "&&";
  case TokenKind::op_or:
    return "||";
  case TokenKind::op_not:
    return "!";
  case TokenKind::op_address:
    return "&";
  case TokenKind::punc_left_paren:
    return "(";
  case TokenKind::punc_right_paren:
    return ")";
  case TokenKind::punc_left_brace:
    return "{";
  case TokenKind::punc_right_brace:
    return "}";
  case TokenKind::punc_left_bracket:
    return "[";
  case TokenKind::punc_right_bracket:
    return "]";
  case TokenKind::punc_comma:
    return ",";
  case TokenKind::punc_colon:
    return ":";
  case TokenKind::punc_semicolon:
    return ";";
  case TokenKind::punc_dot:
    return ".";
  case TokenKind::punc_at:
    return "@";
  case TokenKind::comment:
    return "Comment";
  case TokenKind::end:
    return "End";
  case TokenKind::ast_module:
    return "Module";
  case TokenKind::ast_module_decl:
    return "ModuleDecl";
  case TokenKind::ast_import:
    return "Import";
  case TokenKind::ast_public:
    return "Public";
  case TokenKind::ast_annotation:
    return "Annotation";
  case TokenKind::ast_annotation_decl:
    return "AnnotationDecl";
  case TokenKind::ast_annotation_parameter:
    return "AnnotationParameter";
  case TokenKind::ast_annotation_argument:
    return "AnnotationArgument";
  case TokenKind::ast_function:
    return "Function";
  case TokenKind::ast_parameter:
    return "Parameter";
  case TokenKind::ast_struct:
    return "Struct";
  case TokenKind::ast_field:
    return "Field";
  case TokenKind::ast_type:
    return "Type";
  case TokenKind::ast_pointer_type:
    return "PointerType";
  case TokenKind::ast_array_type:
    return "ArrayType";
  case TokenKind::ast_block:
    return "Block";
  case TokenKind::ast_let:
    return "Let";
  case TokenKind::ast_assign:
    return "Assign";
  case TokenKind::ast_return:
    return "Return";
  case TokenKind::ast_if:
    return "If";
  case TokenKind::ast_when:
    return "When";
  case TokenKind::ast_while:
    return "While";
  case TokenKind::ast_break:
    return "Break";
  case TokenKind::ast_continue:
    return "Continue";
  case TokenKind::ast_asm:
    return "Asm";
  case TokenKind::ast_asm_input:
    return "AsmInput";
  case TokenKind::ast_asm_output:
    return "AsmOutput";
  case TokenKind::ast_asm_option:
    return "AsmOption";
  case TokenKind::ast_expr_stmt:
    return "ExprStmt";
  case TokenKind::ast_literal:
    return "Literal";
  case TokenKind::ast_name:
    return "Name";
  case TokenKind::ast_unary:
    return "Unary";
  case TokenKind::ast_binary:
    return "Binary";
  case TokenKind::ast_call:
    return "Call";
  case TokenKind::ast_index:
    return "Index";
  case TokenKind::ast_member:
    return "Member";
  case TokenKind::ast_group:
    return "Group";
  case TokenKind::ast_meta:
    return "Meta";
  }
  assert("Some token doesn't have a name!");
  return "Unknown";
}
